### ISSUE TITLE
Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

### ISSUE THREAD

**Issue by SohilAhmed** [WhatsAppNETClient/WhatsAppNETClientMultiAccount#1]
getting Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts. even multi device is checked.

**Comment by WhatsAppNETClient** [comment]
Please check this [issue](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues/29)
